changesDir: .changes
unreleasedDir: unreleased
headerPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## [{{.Version}}](https://github.com/sQVe/kamaji/releases/tag/{{.Version}}) - {{.Time.Format "2006-01-02"}}'
kindFormat: "### {{.Kind}}"
changeFormat: "- {{.Body}}{{if .Custom.Issue}} ([#{{.Custom.Issue}}](https://github.com/sQVe/kamaji/issues/{{.Custom.Issue}})){{end}}"
fragmentFileFormat: "{{.Kind | lower}}-{{.Custom.Issue}}{{if not .Custom.Issue}}{{randAlphaNum 8}}{{end}}"

body:
  type: string
  useEditor: true

kinds:
  - label: Added
    auto: minor
  - label: Changed
    auto: minor
  - label: Deprecated
    auto: minor
  - label: Removed
    auto: minor
  - label: Fixed
    auto: patch
  - label: Security
    auto: patch

custom:
  - key: Issue
    label: GitHub issue number
    type: int
    minInt: 1
    optional: true

newlines:
  afterChangelogHeader: 1
  afterChangelogVersion: 1
  afterKind: 0
  beforeKind: 1
  endOfVersion: 1
